socialspy-commands:
  - w
  - tell
  - msg
  - teammsg
  - tm
  - minecraft:w
  - minecraft:tell
  - minecraft:msg
  - minecraft:teammsg
  - minecraft:tm
force-reason: false
muted-forbidden-commands:
  - w
  - tell
  - msg
  - teammsg
  - tm
  - me
  - minecraft:w
  - minecraft:tell
  - minecraft:msg
  - minecraft:teammsg
  - minecraft:tm
  - minecraft:me
features:
  punishments: true
  smodmenu: true
  invsee: true
  enderchestsee: true
  offlinetp: true
  socialspy: true
  vanish: true