# If enabled, punishments can no longer be issued without providing a reason.
force-reason: false

# Allows you to toggle specific plugin features.
features:
  # Should punishments be tracked and executed?
  # Note that disabling this will also disable the SMod menu and
  # /modlogs command since their only use is viewing punishments
  punishments: true
  # Should commands for opening the SMod menu be registered?
  smodmenu: true
  # Should commands for viewing player inventories be registered?
  invsee: true
  # Should commands for viewing player ender chests be registered?
  enderchestsee: true
  # Should commands for teleporting to offline players be registered?
  offlinetp: true
  # Should commands for viewing other players' messaging commands be registered?
  socialspy: true
  # Should players be able to enable vanish mode?
  vanish: true

# A list of commands which will be captured and broadcast
# to players which have SocialSpy enabled (/socialspy).
socialspy-commands:
  - w
  - tell
  - msg
  - teammsg
  - tm
  - minecraft:w
  - minecraft:tell
  - minecraft:msg
  - minecraft:teammsg
  - minecraft:tm

# A list of commands which muted players will not be able to run.
muted-forbidden-commands:
  - w
  - tell
  - msg
  - teammsg
  - tm
  - me
  - minecraft:w
  - minecraft:tell
  - minecraft:msg
  - minecraft:teammsg
  - minecraft:tm
  - minecraft:me